import 'package:aplikasi_uts/detail_page.dart';
import 'package:flutter/material.dart';

class ListDataPage extends StatelessWidget {
  ListDataPage({super.key});

  final List<String> dataProdi = [
    'Desain Komunikasi Visual',
    'Hubungan Internasional',
    'Teknik Informatika',
    'Sistem Informasi',
    'Teknik Mesin',
    'Ilmu Hukum',
    'Manajemen',
    'Teknik Sipil',
    'Kedokteran',
    'Akuntansi',
    'Psikologi',
    'Matematika',
    'Fisika',
    'Jurusan Farmasi',
    'Jurusan Teknik',
    'Desain Komunikasi Visual',
    'Hubungan Internasional',
    'Teknik Informatika',
    'Sistem Informasi',
    'Teknik Mesin',
    'Ilmu Hukum',
    'Manajemen',
    'Teknik Sipil',
    'Kedokteran',
    'Akuntansi',
    'Psikologi',
    'Matematika',
    'Fisika',
    'Jurusan Farmasi',
    'Jurusan Teknik',
    'Desain Komunikasi Visual',
    'Hubungan Internasional',
    'Teknik Informatika',
    'Sistem Informasi',
    'Teknik Mesin',
    'Ilmu Hukum',
    'Manajemen',
    'Teknik Sipil',
    'Kedokteran',
    'Akuntansi',
    'Psikologi',
    'Matematika',
    'Fisika',
    'Jurusan Farmasi',
    'Jurusan Teknik',
    'Desain Komunikasi Visual',
    'Hubungan Internasional',
    'Teknik Informatika',
    'Sistem Informasi',
    'Teknik Mesin',
    'Ilmu Hukum',
    'Manajemen',
    'Teknik Sipil',
    'Kedokteran',
    'Akuntansi',
    'Psikologi',
    'Matematika',
    'Fisika',
    'Jurusan Farmasi',
    'Jurusan Teknik',
    'Desain Komunikasi Visual',
    'Hubungan Internasional',
    'Teknik Informatika',
    'Sistem Informasi',
    'Teknik Mesin',
    'Ilmu Hukum',
    'Manajemen',
    'Teknik Sipil',
    'Kedokteran',
    'Akuntansi',
    'Psikologi',
    'Matematika',
    'Fisika',
    'Jurusan Farmasi',
    'Jurusan Teknik',
    'Desain Komunikasi Visual',
    'Hubungan Internasional',
    'Teknik Informatika',
    'Sistem Informasi',
    'Teknik Mesin',
    'Ilmu Hukum',
    'Manajemen',
    'Teknik Sipil',
    'Kedokteran',
    'Akuntansi',
    'Psikologi',
    'Matematika',
    'Fisika',
    'Jurusan Farmasi',
    'Jurusan Teknik',
    'Desain Komunikasi Visual',
    'Hubungan Internasional',
    'Teknik Informatika',
    'Sistem Informasi',
    'Teknik Mesin',
    'Ilmu Hukum',
    'Manajemen',
    'Teknik Sipil',
    'Kedokteran',
    'Akuntansi',
    'Psikologi',
    'Matematika',
    'Fisika',
    'Jurusan Farmasi',
    'Jurusan Teknik',
    'Desain Komunikasi Visual',
    'Hubungan Internasional',
    'Teknik Informatika',
    'Sistem Informasi',
    'Teknik Mesin',
    'Ilmu Hukum',
    'Manajemen',
    'Teknik Sipil',
    'Kedokteran',
    'Akuntansi',
    'Psikologi',
    'Matematika',
    'Fisika',
    'Jurusan Farmasi',
    'Jurusan Teknik',
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("List Data Page")),
      body: ListView.builder(
        itemCount: dataProdi.length,
        itemBuilder: (constext, index) {
          return ListTile(
            leading: CircleAvatar(child: Text((index + 1).toString())),
            title: Text(dataProdi[index]),
            subtitle: Text('Subtitle untuk ${dataProdi[index]}'),
            onTap: () {
              Navigator.push(context, MaterialPageRoute(builder: (_)=>DetailPage(prodi: dataProdi[index])));
            },
          );
        },
      ),
    );
  }
}
